common_label_names:   # 公共的 label
  - tenant_id
  - namespace
  - env
  - function_api_name
  - language
  - is_long_task
  - is_front_end_access_enabled

schema: # 每个指标的 schema
  function_exec_total:
    name: function_exec_total
    help: "Total number of function executions"
    type: counter
    label_names: [ exec_result, trigger_type ]

  function_exec_duration_milliseconds_total:
    name: function_exec_duration_milliseconds_total
    help: "Total time cost in milliseconds of function executions"
    type: counter
    label_names: [ exec_result, trigger_type ]

  function_exec_duration_milliseconds_histogram:
    name: function_exec_duration_seconds_histogram
    help: "A histogram of latencies per execution"
    type: histogram
    label_names: [ exec_result, trigger_type ]
    buckets: [ 100, 200, 300, 500, 1000, 1500, 2000, 4000, 8000, 10000, 30000, 60000, 300000, 600000, 900000, 3600000, 5400000, 7200000, 9000000 ]

  function_exec_duration_milliseconds_summary:
    name: function_exec_duration_seconds_summary
    help: "A summary of latencies per execution"
    type: summary
    label_names: [ exec_result, trigger_type ]
    objectives:
      0.5: 0.05
      0.9: 0.01
      0.95: 0.005
      0.99: 0.001
      0.999: 0.0001

  function_exec_logs_total:
    name: function_exec_logs_total
    help: "Total number of function execution logs"
    type: counter
    label_names: [ log_level ]