common_label_names: # 公共的 label
  - tenant_id
  - namespace
  - env
  - method
  - path
  - version
  - client_id
  - response_code
  - error_code

schema:
  oapi_call_total:
    name: oapi_call_total
    help: "Total number of Open API calls"
    type: counter

  oapi_call_duration_milliseconds_total:
    name: oapi_call_duration_milliseconds_total
    help: "Total time cost in milliseconds of Open API calls"
    type: counter

  oapi_call_duration_milliseconds_histogram:
    name: oapi_call_duration_milliseconds_histogram
    help: "A histogram of latencies per call"
    type: histogram
    buckets: [50, 100, 200, 300, 500, 1000, 1500, 2000, 4000, 8000]

  oapi_call_duration_milliseconds_summary:
    name: oapi_call_duration_milliseconds_summary
    help: "A summary of latencies per call"
    type: summary
    objectives:
      0.5: 0.05
      0.9: 0.01
      0.95: 0.005
      0.99: 0.001
      0.999: 0.0001

  oapi_call_data_in_bytes_total:
    name: oapi_call_data_in_bytes_total
    help: "Total bytes of request body"
    type: counter

  oapi_call_data_out_bytes_total:
    name: oapi_call_data_out_bytes_total
    help: "Total bytes of response body"
    type: counter
